\set POSTGRES_APPLICATION_USER_PASSWORD `echo ${POSTGRES_APPLICATION_USER_PASSWORD}`
\set POSTGRES_APPLICATION_USER `echo ${POSTGRES_APPLICATION_USER}`
\set POSTGRES_KEYCLOAK_DB `echo ${POSTGRES_KEYCLOAK_DB}`
\set POSTGRES_MEDIA_VAULT_DB `echo ${POSTGRES_MEDIA_VAULT_DB}`

CREATE USER :POSTGRES_APPLICATION_USER WITH ENCRYPTED PASSWORD :'POSTGRES_APPLICATION_USER_PASSWORD';
GRANT USAGE ON SCHEMA public TO :POSTGRES_APPLICATION_USER;

CREATE DATABASE mediavault;
ALTER DATABASE mediavault OWNER TO :POSTGRES_APPLICATION_USER;
GRANT ALL PRIVILEGES ON DATABASE mediavault to :POSTGRES_APPLICATION_USER;

CREATE DATABASE keycloak;
ALTER DATABASE keycloak OWNER TO :POSTGRES_APPLICATION_USER;
GRANT ALL PRIVILEGES ON DATABASE keycloak to :POSTGRES_APPLICATION_USER;