version: '3.8'

volumes:
  postgres-data:
  redis-data:

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-18
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host