name: local-setup

services:
  media-vault:
    build: 
      context: ../../.devcontainer/backend
      dockerfile: Dockerfile
    volumes:
      - ../../:/workspaces/media-vault:cached
      # relative to deployment/development
    command: sleep infinity
    network_mode: "service:nginx"

  media-vault-ui:
    build: 
      context: ../../.devcontainer/website
      dockerfile: Dockerfile
    volumes:
      # relative to deployment/development 
      - ../../:/workspaces/media-vault:cached
    command: sleep infinity

  nginx:
    image: nginx:alpine3.18
    volumes:
      - ../../.devcontainer/nginx/templates:/etc/nginx/templates
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PROXY_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      PROXY_HOST: localhost
      PROXY_PORT: 8181
      MAX_FILE_UPLOAD_SIZE: 5G
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - 8181:8181
