cache:
  redis:
    host: localhost
    port: 6379
    user: ""
    password: "redis"
    db: 0
database:
  postgres:
    host: localhost
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "postgres"
server:
  port: 8090
  host: localhost
  # todo - dev setup doc
  baseURL: http://localhost:5173 
jwt:
  privateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBclpLT29uYUhITXlTSXZMc3Q1YjlDKzZGSmdUZFpqNHJGRk1HY2k5eFZCU3ZkaUkwCnFraDByV25QbTNPYkViT2FSZ0VwZy9pdnNoL1llenpMVFJhd1lsb1pRNk4zNGRadnAxQTh1YStBWmp5bmZtL2EKQWhsT0h6UlByTGd5MWdxUFEwNnV3eHNGY3A1ZlliZG10cDhaa1h3eGpQYXYvMExkK0ZUQThxS1BJNUVVaFZ6Nwp6Z2YwYXhMNlI4cE1NWVZBYm5JMm9SU1IxZllOQ1lnT0VHN0xUaUtCcDE4RWxQU0VFV1E5R0E0VEJadXhBeFduCnFZSW9sUEVMNTE2MEMrTjlHSGsxYXdJMWJyTEErSGFJMDhRYUdNaEFVY0VsbG5xbThJSHI5ZCt2OWxSYy9nRFIKaGlhS244Q2MzR3gvLzhtVExjdFpQUEtQTXBTeFY1NmV6S0hVZXdJREFRQUJBb0lCQURrd05aQ3Z6dHFkU0hUOQpaeU1pTzJPb0JmUzkyNWlwV1JaTU9LNThsVEZuMDF2djd6dy92VG01eUM1bXk2dnNhaU13bE5ZbnBQUGliRGhHCmtwRm1yVnpxWkxLVmRKVlRTdHhzb21WbnZyMXd0SnNERFdodG9BREdBbzVjN2xyNWhiUmVnMVJEWGVzaTVUaFQKN2lLemp3QVJWRjRtbFZ4Y1VyaFViSEpGUHpZdk53dXUwZldQZ3cwTnR6NzNMM3c5dXJuSkFhcnJLblJOaXM1NQpCekV5cU9pa0JOL1ppZElIZk1yV2FHelNHMHhVT0RzTEYwRGVNWUwrcFI5bndONG5rQmVuamlyOEU2TzdSZGJsCnNXMGZwRzJwcGQyZ2RBYTBieUtudVR5aENDN0l2anc2VFhna0dIaEFvS0U2SjRZcE1qUzhJdVEzUGxhZ3RmMmQKL3JPRTUza0NnWUVBMTQyRDB4TzJRMGhnTDBHTjZoN3ErL0dwVVg5MTAxaE1GdjhKSjRqQURCNi9XdUtxQ3Vxawp5WWxsN2FoQTFVL012dmoyNUc2S3NNc0xhRDFwRHYwOU0rUDI4WFpaRUlUNk1LMjZUTURmQXA3c1UyWGxDNmdwCmxNN2xsaFNwTGNyaERwZ3hQSWppUndZbS82ZUhaMDJIaGFtb05WSHhYUHNMTEs4WE1ZMzkyQjhDZ1lFQXppUncKYXhSaG1GT2tPQWVGNVJqRDJJa0Y0eURzTGxzTG1uR1lRNGtHS0Zkdnk1eUwrMi9ZN01LTDJqRnNNRjRMNEltVApzUnA5RnNWekJGN0ZyMnVSd3NWVWtGanU2MTRpRDRsK05yU1I5d0x5RU00bFIxd3RqWlZsSXZxajVDN1VoYy9DClFvRUdMaTg2eUNOSHArSzZONzg0MUN3alpLMGlHd0lpYjZnN2FDVUNnWUVBdUxCSFNCNzJwdlduZkRZRis1amMKTEYwbWYyN2ZyT05WNXNwRXRMd0dHUnhyUnRzNWFUc2RVSlZLWVhRdGdOZnNEYUZTSWUzWkpad0R2U0FKR1UvQQpGZXI0bG5HWjVINmJ4QVBHd2Fic0xkbXZrZEdYakFKZEJtU3o4SURwYUJRUis2aEpYNTNGaTZkbzJOcFpPUmtECnluSFFiMGN6c0VCbGxiYTcvN2l5ekc4Q2dZQURKZ2xWaVYwb1AzYk5xRWZDUlF1UXZoOEo1aEhWYjJ5UThsVTYKQ3RpK092K3BJMzM3M0N4N0NVbXJqbit4aVc0ekFzYnZ1SkRhalMrQmpKVUdaZVUzRFY2S1NlRjBWTjYrVUFKTwpnWm1OSlUxZk5sYlpiUzRBOEp3MzJZNHhTUW5UOVdWcE1LRlFpVVlqa201Z3dSVEpEekdtQS9xU2FoYVFSUXNUCm00VTB4UUtCZ1FDVkd3U1NSaEY0WDRac25pcEc1T1BKYkJKZTFkNmZVRWVEUDYveFB6OVRna2dKUExMdGh1R28Kb3BGM3pUQmZJM1NzQXVGRXFTcWZhS3pDTlkxeFZkK1U0OVBEeTgrb1ZqSUlpMlFRYWhBaWcxR3pqNkFQWVppcgpINmdudDlhRkxNNHc0dVV3bHNTNmkzeU1jWVA2MDQ1YzdHMy96a3IvWVpacnVzWjlKVDh0VFE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  publicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyWktPb25hSEhNeVNJdkxzdDViOQpDKzZGSmdUZFpqNHJGRk1HY2k5eFZCU3ZkaUkwcWtoMHJXblBtM09iRWJPYVJnRXBnL2l2c2gvWWV6ekxUUmF3Cllsb1pRNk4zNGRadnAxQTh1YStBWmp5bmZtL2FBaGxPSHpSUHJMZ3kxZ3FQUTA2dXd4c0ZjcDVmWWJkbXRwOFoKa1h3eGpQYXYvMExkK0ZUQThxS1BJNUVVaFZ6N3pnZjBheEw2UjhwTU1ZVkFibkkyb1JTUjFmWU5DWWdPRUc3TApUaUtCcDE4RWxQU0VFV1E5R0E0VEJadXhBeFducVlJb2xQRUw1MTYwQytOOUdIazFhd0kxYnJMQStIYUkwOFFhCkdNaEFVY0VsbG5xbThJSHI5ZCt2OWxSYy9nRFJoaWFLbjhDYzNHeC8vOG1UTGN0WlBQS1BNcFN4VjU2ZXpLSFUKZXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
session:
  secret: YhcM7EUk7zGDw84XuATE
webUI:
  # development env
  baseURL: "http://localhost:5173"
  directory: "website/dist/"
  # allowedOrigins: 
  #   - localhost:5173
minio:
  host: localhost
  port: 9000
  user: minio-root-user
  password: minio-root-password
  tls: 
    enabled: true
    customRootCAPath: "./.devcontainer/certs/public.crt"
    skipVerify: false
auth-service:
  url: http://localhost:8080/v1/media-service-2
  client:
    ID: media-service-2
    secret: aslkjfdalksdfjlksadfjlkasjlkfjasdfjlkasjd
